### PR TITLE
Array support in patches

### PR DESCRIPTION
**Pull request by michalhainc**
I solved some problems from this area but not sure if correct and if everything works, please have a look at that, hopefully I've not created more problems

### CODE REVIEW

**Comment by niklaswolf** [comment]
Looks good on first sight! 👍 I'll test it further tomorrow 😄

**Comment by niklaswolf** [comment]
I tested it and it works for me now, too (and doesn't break something 😆 ). I am not sure, what replace should do in Arrays and when it should be used (you mentioned this in your comment on the issue)... maybe @endel can bring in some light? ;)

**Comment by michalhainc** [comment]
Hi glad to hear that, I was thinking about this and
I think some parts of 'replace' in arrays should be already in this code handled like this: 

1. compare finds 2 objects at same, these cases may happen:
- they are both cast-able to MessagePackObjectDictionary, then existing recursive call handles our problem - should work, not tested
- they are both simple typed of same type and can be compared -> we can determine if we have a "replace" -> I think this still needs to be implemented
- they are both null -> no patchObject should be generated
- one is null and one is any type not null and vice versa -> clearly a replace - I think this still needs to be implemented

I will test in the evening how these cases are currently handled and let you know afterwards.

**Comment by endel** [comment]
Fixed on 0.5.0 release! https://github.com/gamestdio/colyseus-unity3d/releases/tag/0.5.0

Thanks @michalhainc for the initial implementation. I had to do some changes due to the new [msgpack implementation](https://github.com/deniszykov/msgpack-unity3d/) we're using on this new version.

**Pull request closed without merging**
