### PR TITLE
WebGL support

### PR DESCRIPTION
**Pull request by derwish-pro**
Hi. I have attached the msgpack-unity3d from https://github.com/deniszykov/msgpack-unity3d and now WebGL is working perfectly.

### CODE REVIEW

**Comment by endel** [comment]
Hi @derwish-pro, this is really great, thanks for your pull-request! 

The diff is a bit huge though, do you mind formatting your code using the configuration described here? If your editor supports EditorConfig you can use the autoformat option from your editor. https://github.com/gamestdio/colyseus-unity3d/blob/master/.editorconfig

**Comment by derwish-pro** [comment]
I installed EditorConfig extension in VSCode and reformat changed files but nothing has changed. Any ideas?

**Comment by derwish-pro** [comment]
JetBrais Rider also did not change anything.

**Comment by endel** [comment]
no worries, I'll find some time to test & review this week. it would be easier to see the changeset with the same code format though.

**Comment by derwish-pro** [comment]
Ok, now the code is formatted. Rider helped. VSCode does not work.

**Comment by derwish-pro** [comment]
Noticed the problem. 	
chatRoom.state.Listen("players"... is not working.
OnChangeFallback is called instead.

**Comment by derwish-pro** [comment]
Fixed!

**Comment by endel** [comment]
Thanks! I'll have some time tomorrow to review this :)

**Comment by endel** [comment]
Hey @derwish-pro, sorry, I didn't have time to review this yet. I'd really appreciate if @niklaswolf and @quanglam68 could help us out here.

Here's the report @derwish-pro sent me by email recently:

---
**Derwish**: 

It seems that the problem is how the new MessagePack serializes the dictionary. One byte differs.
 
When I connect to an empty room, `Room.SetState` is called, then MessagePack serializes the empty dictionary, which results in the state of the room in bytes:

> 129 **217 8** 109 101 ...

In the old MessagePack, I get a state like this:

> 129 **168** 109 101 ...

The second and third bytes differ (217 8 - in the new version, 168 - in the old one).
 
Further, when a first message arrives, it is called
`this._previousState = Fossil.Delta.Apply (this._previousState, delta);`
and here is the following. If the room state was not too long in bytes, then this method changes `217 8` to `168`, and then everything works as it should.
And if many bytes were written, then it gives out the error of the checksum.
 
I'll explain it again.
 
The result of `Fossil.Delta.Apply`:
> 129 **168** 109 ...
 
The result of the old `MessagePack.Serialize`:
> 129 **168** 109 ...
 
The result of the new `MessagePack.Serialize`:
> 129 **217 8** 109 ...
 
How to fix it, I do not know. I rely on your help.
I created two branches on the github. This is a chat-client with the old MessagePack and the new one.
https://github.com/derwish-pro/colyseus-unity-chat

**Comment by niklaswolf** [comment]
Hi @endel, unfortunately I'm very busy the next weeks, so better don't rely on me 😆 
But just to make sure: when you refer to the "old" MessagePack, this means the current packages and the "new" one refers to the package mentioned in the first comment?

Furthermore I raise the question if the "new" MessagePack supports Windows Store Apps (UWP), too? Otherwise it would break the current support of the client...
In the teaser-picture in the Unity-Store, WP (Windows Phone) is mentioned, but besides that I can't find any more information about this...

**Comment by endel** [comment]
Hey there,

The byte difference issue has been fixed here: https://github.com/deniszykov/msgpack-unity3d/issues/9

@derwish-pro I'm using the changes you implemented into the branch [0.5.0](https://github.com/gamestdio/colyseus-unity3d/tree/0.5.0) which is compatible with the latest version of the server.

I just need to fix the WebGL build (WebSockets is a problem now), review this merge request (https://github.com/gamestdio/colyseus-unity3d/pull/16), write some tests and we're ready to go!

Thanks a lot

**Comment by endel** [comment]
WebGL export is now working on branch [0.5.0](https://github.com/gamestdio/colyseus-unity3d/tree/0.5.0)!

**Pull request closed without merging**
